remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
title: Crypt0-Mag3's Homepage for InfoSec Musings
description: Your destination for Malware, APT, Pentesting, miscellaneous thoughts and notes on InfoSec
